spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/warehouse_managment?serverTimezone=GMT%2B7&useLegacyDatetimeCode=false&zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: danglinh5920
    driver-class-name: com.mysql.cj.jdbc.Driver
